version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: integrate-labs-sara-website_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: caddy:2.8.4-alpine@sha256:4bcb1d4de6a827aa2eb2517e968e75b542c8fb8a557fbe96d2c8dc39e64fedd8
    restart: on-failure
    entrypoint: ["sh", "-c", "printf ':80 {\n  redir https://sara.integratelabs.app/website 302\n}\n' > /tmp/Caddyfile && caddy run --config /tmp/Caddyfile --adapter caddyfile"]
