version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: integrate-labs-metabase_server_1
      APP_PORT: 3000

  server:
    image: metabase/metabase:v0.63.2.6@sha256:32918a871dfb417caa86f009c8db7d3552a29a4202a5b185e4139f17a0bf2843
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ${APP_DATA_DIR}/data:/metabase-data
