version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: integrate-labs-docuseal_server_1
      APP_PORT: 3000

  server:
    image: docuseal/docuseal:3.1.6@sha256:84b4e296b28738694273e62390c935f3e08f18ad161e19aae90dbfbbb3fa5bb7
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
